config/routes.rb
RailsStarterApp::Application.routes.draw do
  
  get "users/show"

  devise_for :users

  resources :users
  resources :profiles

  

  get "home/index"

  root :to => 'home#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :fax, :phone_1, :phone_2, :url
  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  validates :username,  :uniqueness => { :case_sensitive => false }, :presence => true
  after_create :add_profile
  
  has_one :profile
   
  attr_accessible :login, :username, :email, :password, :password_confirmation, :remember_me, :profile_attributes
  attr_accessor :login
  accepts_nested_attributes_for :profile

  def add_profile
    self.create_profile
  end
  
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  before_filter :authenticate_user!
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = current_user.profile
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate_user!
  
  def index
    @users = User.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
  
  def show
    @user = User.find(params[:id])
    @profile = current_user.profile
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user }
    end
  end
  
  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Welcome to Rails Starter App</h1>
<h2 class="subheader">Built with Rails 3.2.13, Devisea and Foundation</h2>

app/views/layouts/_nav.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to('Rails Starter App', root_url) %></a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if user_signed_in? %>
        <li class="has-dropdown">
          <a href="#">Settings</a>
          <ul class="dropdown">
            <li><%= link_to('View account', user_path(current_user.id)) %></li>
            <li><%= link_to('Edit account', edit_user_registration_path(current_user)) %></li> 
            <li><%= link_to "Edit profile", edit_profile_path(current_user.profile) %></li>
          </ul>
        </li>
        <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
      <% else %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>  
        </li>
        <li>
          <%= link_to('Register', new_user_registration_path)  %>
        </li>
      <% end %>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <% if user_signed_in? %>
        <li><a>Logged in as: <%= current_user.username %></a></li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/_notices.html.erb
<% if notice %>
  <p class="alert-box success radius"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert-box warning radius"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Vaultr</title>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/nav' %>

    <section class="large-12 columns content">
      <div class="row">
        <%= yield %>
      </div>
    </section>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="small-3 columns">
      <%= f.label :phone_1, :class => 'right inline' %>
    </div>    
    <div class="small-9 columns">
      <%= f.text_field :phone_1 %>
    </div> 
  </div>

  <div class="row">
    <div class="small-3 columns">
      <%= f.label :phone_2, :class => 'right inline' %>
    </div>    
    <div class="small-9 columns">
      <%= f.text_field :phone_2 %>
    </div>
  </div>

  <div class="row">
    <div class="small-3 columns"> 
      <%= f.label :fax, :class => 'right inline' %>
    </div>    
    <div class="small-9 columns">
      <%= f.text_field :fax %>
    </div>
  </div>

  <div class="row">
    <div class="small-3 columns"> 
      <%= f.label :url, :class => 'right inline' %>
    </div>    
    <div class="small-9 columns">
      <%= f.text_field :url %>
    </div>
    <div class="small-9 columns small-offset-3">
      <%= f.submit class: 'button'%>
      </div>
    </div>

  <% end %>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="small-8">

    <h1>Editing profile</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @profile %> |
    <%= link_to 'Back', profiles_path %>
  </div>
</div>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>Phone 1</th>
    <th>Phone 2</th>
    <th>Fax</th>
    <th>Url</th>
    <th colspan="3">Actions</th>
  </tr>

  <% @profiles.each do |profile| %>
    <tr>
      <td><%= profile.phone_1 %></td>
      <td><%= profile.phone_2 %></td>
      <td><%= profile.fax %></td>
      <td><%= profile.url %></td>
      <td><%= link_to 'Show', profile %></td>
      <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
      <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<div class="row">
  <div class="small-8"><h1>New profile</h1>

    <%= render 'form' %>

    <%= link_to 'Back', profiles_path %>
  </div>
</div>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Phone 1:</b>
  <%= @profile.phone_1 %>
</p>

<p>
  <b>Phone 2:</b>
  <%= @profile.phone_2 %>
</p>

<p>
  <b>Fax:</b>
  <%= @profile.fax %>
</p>

<p>
  <b>Url:</b>
  <%= @profile.url %>
</p>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th colspan="3">Actions</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to('Edit registration', edit_user_registration_path) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="large-4 columns">
  <h2>Account</h2>
  <p>
    <b>Username:</b>
    <%= @user.username %>
  </p>

  <p>
    <b>Email:</b>
    <%= @user.email %>
  </p>


  <%= link_to('Edit', edit_user_registration_path) %> |
  <%= link_to 'Back', users_path %>
</div>

<div class="large-3 columns">
  <h3>Profile</h3>

  <p>
    <b>Phone 1:</b>
    <%= @profile.phone_1 %>
  </p>

  <p>
    <b>Phone 2:</b>
    <%= @profile.phone_2 %>
  </p>

  <p>
    <b>Fax:</b>
    <%= @profile.fax %>
  </p>

  <p>
    <b>Url:</b>
    <%= @profile.url %>
  </p>


  <%= link_to 'Edit', edit_profile_path(@profile) %> |
  <%= link_to 'Back', profiles_path %>
</div>

<div class="large-3 columns">
  <h4>Other</h4>
</div>